### ISSUE TITLE
Rebase

### ISSUE THREAD

**Issue by Smudge202** [4Com/OctoCity#4]
There hasn't been any changes on this fork since creation, however, the source repo has been updated.

I recommend updating it to herecydev/OctoCity@b315162805977b7d0986edba95d4fc8d5343a6d4

**Comment by herecydev** [comment]
Sounds good, I think @mattridgway is the only one with rights to do this

**Comment by herecydev** [comment]
Never mind, I figured it out. Some rebasing straight onto master.

![image](https://cloud.githubusercontent.com/assets/11328618/7087294/b360e3de-df81-11e4-98d7-49d73e70c685.png)

**Comment by Smudge202** [comment]
For future ref, this repo has a dev branch.  Rebase the dev branch and PR the master (else the bad man will take away push rights!)
